# Generated by Django 4.2.3 on 2023-09-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_category', models.CharField(max_length=30, verbose_name=' نام دسته بندی')),
                ('url', models.CharField(max_length=40, verbose_name='ادرس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Blog_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='موضوع')),
                ('short_description', models.CharField(max_length=50, verbose_name='توضیح کوتاه')),
                ('list_description', models.CharField(default='', max_length=100, verbose_name='توضیحات بلاگ لیست')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('image', models.ImageField(upload_to='image_blog/%Y/%b', verbose_name='عکس')),
                ('date', models.DateField(auto_now_add=True, verbose_name='تاریخ')),
                ('slug', models.SlugField(blank=True, default='', null=True, unique=True)),
                ('blog_preview', models.BooleanField(default=False, verbose_name='پیش نمایش بلاگ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_modul.blog_category', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'بلاگ',
                'verbose_name_plural': 'بلاگ ها',
            },
        ),
    ]
