# Generated by Django 4.2.3 on 2023-10-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog_modul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=30, verbose_name='نام')),
                ('email', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('image', models.ImageField(upload_to='blog_comment/%Y/%b', verbose_name='عکس')),
                ('text', models.TextField(verbose_name='پیام شما')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('admin_approval', models.BooleanField(default=False, verbose_name='تایید ادمین')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog_modul.blog_model', verbose_name='بلاگ')),
                ('replace', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog_modul.blog_comment', verbose_name='پاسخ')),
            ],
            options={
                'verbose_name': 'کامنت',
                'verbose_name_plural': 'کامنت ها',
            },
        ),
    ]
