# Generated by Django 4.2.3 on 2023-10-02 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_modul', '0002_blog_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_model',
            name='image',
            field=models.ImageField(blank=True, upload_to='image_blog/%Y/%b', verbose_name='عکس'),
        ),
    ]
