# Generated by Django 5.0.3 on 2024-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_modul', '0003_alter_blog_model_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog_comment',
            name='image',
            field=models.ImageField(blank=True, default='', null=True, upload_to='blog_comment/%Y/%b', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='blog_model',
            name='image',
            field=models.ImageField(upload_to='image_blog/%Y/%b', verbose_name='عکس'),
        ),
    ]
