# Generated by Django 4.2.3 on 2023-08-22 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام')),
                ('logo', models.FileField(upload_to='logo/%Y/%b')),
                ('language', models.BooleanField(default=False, verbose_name='زبان')),
                ('twitter', models.URLField(null=True, verbose_name='ادرس اکانت توییتر')),
                ('youtube', models.URLField(null=True, verbose_name='ادرس اکانت یوتیوب')),
                ('facebook', models.URLField(null=True, verbose_name='ادرس اکانت فیسبوک')),
                ('instagram', models.URLField(null=True, verbose_name='ادرس اکانت اینستاگرام')),
            ],
        ),
    ]
