# Generated by Django 4.2.3 on 2023-08-22 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home_model', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'verbose_name': 'خانه', 'verbose_name_plural': 'تنظیمات صغحه خانه'},
        ),
    ]
