# Generated by Django 4.2.3 on 2023-08-22 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_model', '0003_alter_home_facebook_alter_home_instagram_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='facebook',
            field=models.URLField(blank=True, default='www.facebook.com', verbose_name='ادرس اکانت فیسبوک'),
        ),
        migrations.AlterField(
            model_name='home',
            name='instagram',
            field=models.URLField(blank=True, default='www.instagram.com', verbose_name='ادرس اکانت اینستاگرام'),
        ),
        migrations.AlterField(
            model_name='home',
            name='twitter',
            field=models.URLField(blank=True, default='www.twitter.com', verbose_name='ادرس اکانت توییتر'),
        ),
        migrations.AlterField(
            model_name='home',
            name='youtube',
            field=models.URLField(blank=True, default='www.youtube.com', verbose_name='ادرس اکانت یوتیوب'),
        ),
    ]
