# Generated by Django 4.2.3 on 2023-08-22 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_model', '0004_alter_home_facebook_alter_home_instagram_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_social', models.ImageField(upload_to='icon_social_Home/%Y/%b', verbose_name='ایکون شبکه اجتماعی')),
                ('url_social', models.URLField(verbose_name='ادرس شبکه اجتماعی')),
            ],
        ),
        migrations.RemoveField(
            model_name='home',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='home',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='home',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='home',
            name='youtube',
        ),
        migrations.AddField(
            model_name='home',
            name='social_network',
            field=models.ManyToManyField(blank=True, to='home_model.social', verbose_name='شبکه های اجتماعی'),
        ),
    ]
