# Generated by Django 4.2.3 on 2023-08-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_model', '0005_social_remove_home_facebook_remove_home_instagram_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'verbose_name': 'شبکه اجتماعی', 'verbose_name_plural': 'شبکه های اجتماعی'},
        ),
        migrations.AddField(
            model_name='social',
            name='name_social',
            field=models.CharField(blank=True, max_length=50, verbose_name='نام شبکه اجتماعی'),
        ),
    ]
