# Generated by Django 4.2.3 on 2023-08-22 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_model', '0006_alter_social_options_social_name_social'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='home',
            name='social_network',
        ),
        migrations.AddField(
            model_name='home',
            name='facebook',
            field=models.URLField(blank=True, verbose_name='ادرس اکانت فیسبوک'),
        ),
        migrations.AddField(
            model_name='home',
            name='instagram',
            field=models.URLField(blank=True, verbose_name='ادرس اکانت اینستاگرام'),
        ),
        migrations.AddField(
            model_name='home',
            name='twitter',
            field=models.URLField(blank=True, verbose_name='ادرس اکانت توییتر'),
        ),
        migrations.AddField(
            model_name='home',
            name='youtube',
            field=models.URLField(blank=True, verbose_name='ادرس اکانت یوتیوب'),
        ),
        migrations.DeleteModel(
            name='social',
        ),
    ]
