# Generated by Django 4.2.3 on 2023-08-24 08:21

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home_model', '0007_remove_home_social_network_home_facebook_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='language',
            field=models.UUIDField(default=uuid.UUID('ae271afc-e7b9-445f-9aea-980398077f64'), editable=False, verbose_name='زبان'),
        ),
    ]
