# Generated by Django 4.2.3 on 2023-08-24 08:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('home_model', '0008_alter_home_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='language_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='کدزبان'),
        ),
        migrations.AlterField(
            model_name='home',
            name='language',
            field=models.BooleanField(default=False, verbose_name='زبان'),
        ),
    ]
