# Generated by Django 4.2.3 on 2023-09-10 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_model', '0011_alter_home_language_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='home',
            name='en_name',
            field=models.CharField(max_length=50, null=True, verbose_name='نام به انگلیسی'),
        ),
    ]
