# Generated by Django 4.2.3 on 2023-09-26 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PortfolioCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان دسته بندی')),
                ('url', models.CharField(max_length=30, verbose_name='ادرس')),
            ],
            options={
                'verbose_name': 'دسته بندی',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_project', models.CharField(max_length=30, verbose_name='نام پروژه')),
                ('icon', models.CharField(default='fa fa-image', max_length=50, verbose_name='ایکون')),
                ('image', models.ImageField(blank=True, upload_to='portfolio/%Y/%b', verbose_name='عکس')),
                ('video', models.FileField(blank=True, help_text='در این قسمت می توانید ویدیو اضافه کنید', upload_to='portfolio/%Y/%b', verbose_name='ویدیو')),
                ('slug', models.SlugField(blank=True, default='project', null=True, unique=True, verbose_name='اسلاگ')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio_modul.portfoliocategory', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'نمونه کار',
                'verbose_name_plural': 'نمونه کارها',
            },
        ),
    ]
