# Generated by Django 5.0.3 on 2024-04-01 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_modul', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='ادرس'),
        ),
    ]
