# Generated by Django 5.0.3 on 2024-04-01 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_modul', '0002_portfolio_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='ادرس'),
        ),
    ]
