# Generated by Django 5.0.3 on 2024-03-31 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume_educational',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(max_length=30, verbose_name='مقطع تحصیلی')),
                ('field_study', models.CharField(max_length=50, verbose_name='رشته تحصیلی')),
                ('start_time', models.DateField(verbose_name='زمان شروع')),
                ('end_time', models.DateField(verbose_name='زمان اتمام')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سابقه تحصیلی',
                'verbose_name_plural': 'سوابق تحصیلی',
            },
        ),
        migrations.CreateModel(
            name='Resume_model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(max_length=30, verbose_name='کار')),
                ('company', models.CharField(max_length=50, verbose_name='شرکت')),
                ('start_time', models.DateField(verbose_name='زمان شروع')),
                ('end_time', models.DateField(verbose_name='زمان اتمام')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'سابقه کاری',
                'verbose_name_plural': 'سوابق کاری',
            },
        ),
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=30, verbose_name='نام مهارت')),
                ('percent', models.IntegerField(default=100, verbose_name='درصد توانایی')),
                ('type_skill', models.CharField(choices=[('circle', 'دایره'), ('linear', 'خطی')], max_length=10, verbose_name='نوع نمودار')),
                ('color', models.CharField(default='#fff', max_length=10, verbose_name='رنگ')),
            ],
            options={
                'verbose_name': 'مهارت',
                'verbose_name_plural': 'مهارت ها',
            },
        ),
        migrations.CreateModel(
            name='Work_process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_work', models.IntegerField(verbose_name='شماره مرحله')),
                ('title', models.CharField(max_length=30, verbose_name='عنوان')),
                ('description', models.CharField(max_length=150, verbose_name='توضیحات کوتاه')),
            ],
            options={
                'verbose_name': 'پروسه کار',
                'verbose_name_plural': 'پروسه کاری',
            },
        ),
    ]
