# Generated by Django 4.2.3 on 2023-08-22 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='Favorites',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Issue', models.CharField(max_length=80, verbose_name='موضوع')),
            ],
        ),
        migrations.CreateModel(
            name='AboutModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, verbose_name='نام و نام خانوادگی')),
                ('country', models.CharField(max_length=30, verbose_name='کشور')),
                ('city', models.CharField(max_length=30, verbose_name='شهر')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('experience', models.FloatField(verbose_name='تجربه')),
                ('finished', models.IntegerField(verbose_name='اتمام یافته')),
                ('resume', models.FileField(upload_to='pdf/%Y/%b', verbose_name='رزومه')),
                ('image', models.ImageField(upload_to='image/%Y/%b', verbose_name='عکس')),
                ('condition', models.ManyToManyField(to='about_modul.condition', verbose_name='وضعیت')),
                ('favorites', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_modul.favorites', verbose_name='علایق')),
            ],
        ),
    ]
