# Generated by Django 4.2.3 on 2023-08-22 13:18

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_prices', models.CharField(max_length=30, verbose_name='عنوان')),
                ('logo_prices', models.ImageField(upload_to='icon_about/%Y/%b', verbose_name='ایکون')),
                ('price', models.ImageField(upload_to='', verbose_name='قیمت')),
                ('period', models.CharField(choices=[('monthly', 'ماهانه'), ('yearly', 'سالانه'), ('telecommuting', 'دورکاری')], max_length=50, verbose_name='بازه زمانی')),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo_service', models.ImageField(upload_to='logo_about/%Y/%b', verbose_name='لوگو')),
                ('title_service', models.CharField(max_length=30, verbose_name='عنوان خدمات')),
                ('description_service', models.TextField(verbose_name='توضیحات')),
            ],
        ),
        migrations.RenameField(
            model_name='condition',
            old_name='title',
            new_name='title_condition',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='favorites',
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='image',
            field=models.ImageField(upload_to='image_about/%Y/%b', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='resume',
            field=models.FileField(upload_to='pdf_about/%Y/%b', verbose_name='رزومه'),
        ),
        migrations.CreateModel(
            name='Opinions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_opinions', models.CharField(max_length=50, verbose_name='نام ونام خانوادگی')),
                ('score', models.PositiveIntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5)])),
                ('description_opinions', models.TextField(verbose_name='توضیحات')),
                ('service_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about_modul.service', verbose_name='نوع خدمات')),
            ],
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='opinions',
            field=models.ManyToManyField(to='about_modul.opinions', verbose_name='دیدگاه مشتریان'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='prices',
            field=models.ManyToManyField(to='about_modul.prices', verbose_name='قیمت ها'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='service',
            field=models.ManyToManyField(to='about_modul.service', verbose_name='خدمات'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='favorites',
            field=models.ManyToManyField(to='about_modul.favorites', verbose_name='علایق'),
        ),
    ]
