# Generated by Django 4.2.3 on 2023-08-22 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0002_prices_service_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutmodel',
            options={'verbose_name': 'درباره', 'verbose_name_plural': 'درباره من'},
        ),
        migrations.AlterModelOptions(
            name='condition',
            options={'verbose_name': 'وضعیت', 'verbose_name_plural': 'وضعیت ها'},
        ),
        migrations.AlterModelOptions(
            name='favorites',
            options={'verbose_name': 'علایق', 'verbose_name_plural': 'علاقه مندی ها'},
        ),
        migrations.AlterModelOptions(
            name='opinions',
            options={'verbose_name': 'دیگاه مشتری', 'verbose_name_plural': 'دیدگاه مشتریان'},
        ),
        migrations.AlterModelOptions(
            name='prices',
            options={'verbose_name': 'قیمت', 'verbose_name_plural': 'قیمت ها'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'خدمات', 'verbose_name_plural': 'خدمات'},
        ),
    ]
