# Generated by Django 4.2.3 on 2023-08-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0003_alter_aboutmodel_options_alter_condition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='favorites',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icon_favorites/', verbose_name='موضوع'),
        ),
    ]
