# Generated by Django 4.2.3 on 2023-08-22 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0004_favorites_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='icon',
            field=models.ImageField(blank=True, upload_to='icon_favorites/', verbose_name='ایکون'),
        ),
    ]
