# Generated by Django 4.2.3 on 2023-08-22 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0005_alter_favorites_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='price',
            field=models.IntegerField(verbose_name='قیمت'),
        ),
    ]
