# Generated by Django 4.2.3 on 2023-09-10 19:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0006_alter_prices_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='condition',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='condition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about_modul.condition', verbose_name='وضعیت'),
        ),
    ]
