# Generated by Django 4.2.3 on 2023-09-10 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0007_remove_aboutmodel_condition_aboutmodel_condition'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutmodel',
            name='favorites',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='opinions',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='prices',
        ),
        migrations.RemoveField(
            model_name='aboutmodel',
            name='service',
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='favorites',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about_modul.favorites', verbose_name='علایق'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='opinions',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about_modul.opinions', verbose_name='دیدگاه مشتریان'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='prices',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about_modul.prices', verbose_name='قیمت ها'),
        ),
        migrations.AddField(
            model_name='aboutmodel',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='about_modul.service', verbose_name='خدمات'),
        ),
    ]
