# Generated by Django 4.2.3 on 2023-09-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0008_remove_aboutmodel_favorites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favorites',
            name='icon',
            field=models.CharField(blank=True, max_length=50, verbose_name='ایکون'),
        ),
    ]
