# Generated by Django 4.2.3 on 2023-09-10 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0009_alter_favorites_icon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='logo_prices',
            field=models.CharField(max_length=50, null=True, verbose_name='ایکون'),
        ),
        migrations.AlterField(
            model_name='service',
            name='logo_service',
            field=models.CharField(max_length=50, verbose_name='لوگو'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title_service',
            field=models.CharField(max_length=30, null=True, verbose_name='عنوان خدمات'),
        ),
    ]
