# Generated by Django 4.2.3 on 2023-09-10 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0010_alter_prices_logo_prices_alter_service_logo_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinions',
            name='image_opinions',
            field=models.ImageField(null=True, upload_to='image_opinions/%Y/%b', verbose_name='عکس'),
        ),
    ]
