# Generated by Django 4.2.3 on 2023-09-12 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0011_opinions_image_opinions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prices',
            name='period',
            field=models.CharField(choices=[('ماهانه', 'ماهانه'), ('سالانه', 'سالانه'), ('دورکاری', 'دورکاری')], max_length=50, verbose_name='بازه زمانی'),
        ),
    ]
