# Generated by Django 4.2.3 on 2023-09-14 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0012_alter_prices_period'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='experience',
            field=models.ImageField(upload_to='', verbose_name='تجربه'),
        ),
    ]
