# Generated by Django 4.2.3 on 2023-09-14 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_modul', '0013_alter_aboutmodel_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutmodel',
            name='experience',
            field=models.PositiveIntegerField(verbose_name='تجربه'),
        ),
        migrations.AlterField(
            model_name='aboutmodel',
            name='finished',
            field=models.PositiveIntegerField(verbose_name='اتمام یافته'),
        ),
    ]
